### ISSUE TITLE
Ead2DCterms : "This is not a valid plugin"

### ISSUE THREAD

**Issue by prkf75** [Daniel-KM/Ead2DCterms#1]
Hi,
I'm using Omeka 2.5.1.
I'm trying to install Ead2DCterms and Ead4Omeka.
Everything goes fine until i refresh my plugin page on my Omeka website : neither Ead2DCterms nor Ead4Omeka are considered as "valid plugins" by my platform.
I looked around and checked if it was a permission issue (and typed sudo chown -R www-data:www-data /var/www before unzipping and installing the add-ons), but the error message is the same.
Do you have an idea about what causes the install to fail ?
Thanks in advance !
A.

**Comment by Daniel-KM** [comment]
Hi, 

When installing from github, you have to rename the name of the folder of the plugin from `Ead4Omeka-master` to `Ead`. The tool `Ead2DCterms` should be installed in the subfolder `libraires/external`. This is an xsl sheet, not a plugin, so it can be used separately somewhere else too.

**Comment by prkf75** [comment]
Hi,
It works! I noticed that Ead2DCterms is required to make Ead4Omeka work.
Thanks a lor for your advice,
A.
